### PR TITLE
beta 20 compatibility

### PR DESCRIPTION
**Pull request by MakeilaLundy**

### CODE REVIEW

**Comment by leevigraham** [comment]
Thanks @MakeilaLundy!

Looks like beta20 hasn't been released yet?

**Comment by leevigraham** [comment]
Relevant: https://github.com/craftcms/cms/blob/develop/CHANGELOG-v3.md#unreleased-critical and #1733.

**Comment by MakeilaLundy** [comment]
it will be released soon!

**Comment by leevigraham** [comment]
@MakeilaLundy Can you merge master into your PR? I added a new embed field that needs checking as well.

**Comment by leevigraham** [comment]
Merged into feature/beta.20

**Pull request closed without merging**
